Update pre-commit

diff --git a/MLForensics/MLForensics-farzana/pre-commit b/MLForensics/MLForensics-farzana/pre-commit
--- a/MLForensics/MLForensics-farzana/pre-commit
+++ b/MLForensics/MLForensics-farzana/pre-commit
@@ -9,10 +9,10 @@
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
+    # Initial commit: diff against an empty tree object
+    against=$(git hash-object -t tree /dev/null)
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -25,13 +25,13 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
+    cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -42,14 +42,19 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-	exit 1
+    exit 1
 fi
 
-bandit **/*.py -r -a file -f csv -o vulnerabilities.csv
-if [ $? -eq 0 ]; then
-	echo "bandit found no vulnerabilities"
+# Run Bandit and check for vulnerabilities
+bandit_output=$(bandit **/*.py -r -f csv -o vulnerabilities.csv)
+bandit_exit_code=$?
+
+if [ $bandit_exit_code -eq 0 ]; then
+    echo "Bandit found no vulnerabilities"
 else
-	echo "bandit found vulnerabilities"
+    echo "Bandit found vulnerabilities"
+    echo "$bandit_output"  # Print Bandit output for visibility
+    exit 1  # Exit with a non-zero status to stop the commit
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
